controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Ajout manuel de la route pour EasyAdmin Dashboard
admin_dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index
